In [55]:
import pandas as pd

In [121]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot
%matplotlib inline
plt.style.use('ggplot')

from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
from plotly.subplots import make_subplots
import plotly.graph_objs as go
import re
import tensorflow as tf


# Model 
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from imblearn.under_sampling import RandomUnderSampler
from sklearn.svm import LinearSVC, SVC
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler, NearMiss, TomekLinks, AllKNN
from imblearn.combine import SMOTETomek, SMOTEENN
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC, LinearSVC
from xgboost import XGBClassifier

from sklearn.metrics import f1_score
from sklearn import metrics


import warnings
warnings.filterwarnings('ignore')

In [56]:
df=pd.read_csv(r"D:\vs code\Datathon_TrainData_org.csv")

In [57]:
df.head()

Country              Date         Speaker  \
0  Russia        24-01-2000  Vladimir Putin   
1     USA  09-09-2021 00:00       Joe Biden   
2  Russia        24-12-2004  Vladimir Putin   
3     USA        14-08-2014    Barack Obama   
4     USA  26-03-2021 00:00       Joe Biden   

                                            Headline  \
0  Speech at a conference of the heads of republi...   
1  Remarks by President Biden on Fighting the COV...   
2  Excerpts from the Opening Speech at a Session ...   
3                       \nStatement by the President   
4  Statement by President Biden on the Attack on ...   

                                      Text_of_Speech Designation  \
0  Esteemed Mr Lebedev,\n\nLadies and Gentlemen:\...   President   
1  THE PRESIDENT:  Good evening, my fellow Americ...   President   
2  Good afternoon, dear colleagues,\n\nOur meetin...   President   
3  Good afternoon, everybody. This sound system i...   President   
4  More Americans voted in the 2020 elections tha...   President   

  Running President/PM                                        Speech Link  \
0       Vladimir Putin  http://en.kremlin.ru/events/president/transcri...   
1            Joe Biden  https://www.whitehouse.gov/briefing-room/speec...   
2       Vladimir Putin  http://en.kremlin.ru/events/president/transcri...   
3         Barack Obama  https://obamawhitehouse.archives.gov/the-press...   
4            Joe Biden  https://www.whitehouse.gov/briefing-room/speec...   

    Emotion                Context  
0     UPSET                 OTHERS  
1  OPTIMISM            DEVELOPMENT  
2   NEUTRAL            DEVELOPMENT  
3   NEUTRAL  INTERNATIONAL AFFAIRS  
4     UPSET                 OTHERS

In [58]:
data=df.drop(['Country','Date','Speaker','Designation','Running President/PM','Speech Link','Context'],axis=1)

In [59]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [60]:
data['text']=data['Headline']+' '+data['Text_of_Speech']

In [61]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [62]:
data=data.dropna()

In [63]:
data=data.reset_index()

In [65]:
def clean_texts(text):
    """Removes digits, words containing digits, punctuations, special characters, extra spaces and links from text

    Args:
        text (str): raw texts
    Returns:
        text (str) : cleaned texts
    """
    #removes links
    text = re.sub(r'http*\S+', '', text)
    #removes digits 
    text = re.sub('\d+','', text)
    #removes punctuations and special characters
    text = re.sub('[^a-zA-Z]+', ' ', text)
    return text

In [66]:
data['cleaned_texts'] = data['text'].apply(clean_texts)  

In [158]:
data.to_csv('sample_data.csv', index=False)

In [67]:
from tqdm import tqdm

In [ ]:
import pandas as pd
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize as st
from nltk.stem import WordNetLemmatizer
import re
lemmatizer = WordNetLemmatizer()

In [68]:
texts = data['cleaned_texts']
#convert to dataframe
texts = pd.DataFrame(texts)
#create empty list to hold the final output
corpus = []
#loop through each row of comments
for i in tqdm(range(0, len(texts))):
    #tokenize the text
    review = texts['cleaned_texts'][i].split()
    #remove stopwords and lemmatize
    text_stopwords_lemmatized = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    #combine the tokenized texts
    text_stopwords_lemmatized = ' '.join(text_stopwords_lemmatized)
    #put final result into the corpus list
    
    corpus.append(text_stopwords_lemmatized)

100%|██████████████████████████████████████████████████████████████████████████████| 1605/1605 [05:58<00:00,  4.48it/s]


In [169]:
data['c_t']=corpus

In [171]:
data.to_csv('sample_data1.csv', index=False)

In [77]:
y = label_encoder.fit_transform(data['Emotion'])

In [69]:
from sklearn.feature_extraction.text import  TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [78]:
X_train, X_test, y_train, y_test = train_test_split(np.asarray(corpus), y, test_size = 0.2, random_state = 24)

In [80]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [92]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score,classification_report

In [82]:
tfidf = TfidfVectorizer()
model = RandomForestClassifier()

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
param_dist={'max_depth':[3,5,7,10,None],
              'n_estimators':[10,50,100,150,200,250,300,400,500],
               'criterion':['gini','entropy'],
               'bootstrap':[True,False],
              }
rf_model = RandomForestClassifier(class_weight='balanced', random_state = 42)
search_clfr = RandomizedSearchCV(rf_model, param_distributions = param_dist, n_jobs=-1, n_iter = 10, cv = 3, verbose =1)
search_clfr.fit(x_train, y_train)
search_clfr.best_estimator_

In [88]:
model = RandomForestClassifier()

In [89]:
pipe_line = Pipeline([
                      ('tfidf', tfidf),
                      ('model', model)
])

In [90]:
pipe_line.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('model', RandomForestClassifier())])

In [93]:
pred = pipe_line.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.58      0.57      0.57        86
           1       0.48      0.61      0.53        99
           2       0.41      0.46      0.43        87
           3       0.75      0.18      0.30        49

    accuracy                           0.49       321
   macro avg       0.55      0.45      0.46       321
weighted avg       0.53      0.49      0.48       321



In [94]:
print(confusion_matrix(y_test, pred))

[[49 17 19  1]
 [ 9 60 30  0]
 [14 31 40  2]
 [13 18  9  9]]


In [95]:
import xgboost
from xgboost import XGBClassifier

In [96]:
xgb_model = XGBClassifier()
xgb_pipe_line = Pipeline([
                      ('tfidf', tfidf),
                      ('model', xgb_model)
])

In [98]:
xgb_pipe_line.fit(X_train, y_train)

D:\anacoda\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[00:41:31] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('model',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, enable_categorical=False,
                               gamma=0, gpu_id=-1, importance_type=None,
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=8, num_parallel_tree=1,
                               objective='multi:softprob', predictor='auto',
                               random_state=0, reg_alpha=0, reg_lambda=1,
                               scale_pos_weight=None, subsample=1,
                               tree_method='exact', validate_parameters=1,
                               verbosity=None))])

In [99]:
pred = xgb_pipe_line.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.59      0.60      0.60        86
           1       0.49      0.54      0.51        99
           2       0.44      0.48      0.46        87
           3       0.61      0.35      0.44        49

    accuracy                           0.51       321
   macro avg       0.53      0.49      0.50       321
weighted avg       0.52      0.51      0.51       321



In [100]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [113]:
nb_pipe_line = Pipeline([
                      ('tfidf', tfidf),
                      ('model', nb)
])

In [114]:
nb_pipe_line.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('model', MultinomialNB())])

In [115]:
pred = nb_pipe_line.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.73      0.35      0.47        86
           1       0.42      0.63      0.51        99
           2       0.34      0.53      0.42        87
           3       0.00      0.00      0.00        49

    accuracy                           0.43       321
   macro avg       0.37      0.38      0.35       321
weighted avg       0.42      0.43      0.40       321



D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [105]:
from sklearn.feature_extraction.text import  CountVectorizer

In [106]:
cv=CountVectorizer()

In [108]:
nb_pipe_line_cv = Pipeline([
                      ('cv', cv),
                      ('model', nb)
])

In [109]:
nb_pipe_line_cv.fit(X_train, y_train)

Pipeline(steps=[('cv', CountVectorizer()), ('model', MultinomialNB())])

In [116]:
pred = nb_pipe_line_cv.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.74      0.33      0.45        86
           1       0.42      0.59      0.49        99
           2       0.33      0.55      0.42        87
           3       0.00      0.00      0.00        49

    accuracy                           0.42       321
   macro avg       0.37      0.37      0.34       321
weighted avg       0.42      0.42      0.38       321



D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [111]:
xgb_pipe_line_cv = Pipeline([
                      ('cv', cv),
                      ('model', xgb_model)
])

In [112]:
xgb_pipe_line_cv.fit(X_train, y_train)

D:\anacoda\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[00:47:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('cv', CountVectorizer()),
                ('model',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, enable_categorical=False,
                               gamma=0, gpu_id=-1, importance_type=None,
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=8, num_parallel_tree=1,
                               objective='multi:softprob', predictor='auto',
                               random_state=0, reg_alpha=0, reg_lambda=1,
                               scale_pos_weight=None, subsample=1,
                               tree_method='exact', validate_parameters=1,
                               verbosity=None))])

In [117]:
pred = xgb_pipe_line_cv.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.56      0.51      0.54        86
           1       0.42      0.49      0.46        99
           2       0.38      0.41      0.39        87
           3       0.61      0.39      0.47        49

    accuracy                           0.46       321
   macro avg       0.49      0.45      0.47       321
weighted avg       0.48      0.46      0.46       321



In [122]:
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', None)
])

# Define the models and their hyperparameters
models = {
    
    'Multinomial Naive Bayes' : {
        'clf': [MultinomialNB()],
            'clf__alpha': [0.5, 1.0, 1.5],
    },
    'Logistic Regression' : {
        'clf': [LogisticRegression(max_iter=1000, multi_class ="multinomial" )],
            'clf__penalty': ['l1', 'l2'],
            'clf__C': [0.1, 1.0, 2.0],
    },
    
    'DecisionTree Classifier' : {
        'clf': [DecisionTreeClassifier()],
            'clf__max_depth': [10, 50, 100, None],
            'clf__min_samples_split': [2, 5, 10],
            'clf__min_samples_leaf': [1, 2, 4]
    },
    'Support Vector Classification' : {
        'clf': [SVC()],
            'clf__C': [0.1, 0.5, 1.0, 2.0],
            'clf__kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
            'clf__degree': [2, 3, 4, 5],
            'clf__gamma': ['scale', 'auto']
    },
    'LinearSVC' : {
        'clf': [LinearSVC(max_iter=1000)],
            'clf__C': [0.1, 0.5, 1.0, 2.0],
            'clf__penalty': ['l1', 'l2']
    }, 
    'RandomForest Classifier' : {
        'clf': [RandomForestClassifier()],
            'clf__n_estimators': [50, 100, 150],
            'clf__max_depth': [5, 10, 15]
    },
    'KNeighbors Classifier' : {
        'clf': [KNeighborsClassifier()],
            'clf__n_neighbors': [3, 5, 7],
            'clf__leaf_size': [20, 30, 40]
    },
    'XGBoost Classifier' : {
        'clf': [XGBClassifier()],
            'clf__n_estimators': [50, 100, 150],
            'clf__max_depth': [5, 10, 15]
        
    }
    
}

In [123]:
best_score = 0
best_model = None

for model_name, model in models.items():
    print(f'Tuning {model_name}')
    
    # Perform a grid search to find the best hyperparameters for the current model
    grid_search = GridSearchCV(pipeline, model, cv=5, n_jobs=-1, scoring='f1_macro')
    grid_search.fit(X_train, y_train)
    
    # Set the best hyperparameters for the current model
    best_params = grid_search.best_params_
    
    # Update the pipeline with the best hyperparameters
    pipeline.set_params(**best_params)
    
    # Fit the model on the training set
    pipeline.fit(X_train, y_train)
    
    # Evaluate the model on the test set
    y_pred = pipeline.predict(X_test)
    f1Score = metrics.f1_score(y_test, y_pred, average='micro')
    
    print('Best F1 score:', f1Score)
    
    if f1Score > best_score:
        best_score = f1Score
        best_model = grid_search.best_estimator_
    

        
print("Best model: ", best_model.named_steps['clf'].__class__.__name__)
print("Best F1 score: ", best_score)

Tuning Multinomial Naive Bayes
Best F1 score: 0.43613707165109034
Tuning Logistic Regression
Best F1 score: 0.5295950155763239
Tuning DecisionTree Classifier
Best F1 score: 0.40186915887850466
Tuning Support Vector Classification
Best F1 score: 0.5109034267912772
Tuning LinearSVC
Best F1 score: 0.5046728971962616
Tuning RandomForest Classifier
Best F1 score: 0.46105919003115264
Tuning KNeighbors Classifier
Best F1 score: 0.4423676012461059
Tuning XGBoost Classifier
[01:59:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[02:01:04] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'm

In [124]:
!pip install gensim

  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20445 sha256=f302f405460f4b84b708cdd0498d5740c79ffb8c6e2580f84bebad2379f9cace
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\99\66\48\d7ce0c6927f6abf167bbcdee537affc7b92c03632f78028411
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3530 sha256=fa63e2a6c5b7d9ac6c18ae525d85646b72feff43f222a5f1f87be8a44362ef67
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\d9\c7\71\db1d4646d963b34c530667501d3d6f34c0825eaffae2f0f2cb
Successfully built fst-pso miniful


In [125]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [126]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [127]:
import gensim
model3 = gensim.models.Word2Vec(words,window=5,min_count=2)

In [129]:
model3.wv.similar_by_word('art')

[('literature', 0.8525446653366089),
 ('excellence', 0.849727213382721),
 ('outlet', 0.8333239555358887),
 ('archaeological', 0.8266620635986328),
 ('swallowing', 0.8257982134819031),
 ('fitness', 0.8218396306037903),
 ('bio', 0.8200987577438354),
 ('outpatient', 0.8198175430297852),
 ('demonstration', 0.8186842203140259),
 ('outdoor', 0.8186576962471008)]

In [130]:
def avg_word2vec(doc):
    return np.mean([model3.wv[word] for word in doc if word in model3.wv.index_to_key], axis=0)

In [131]:
X3 = []
for i in tqdm(range(len(words))):
    X3.append(avg_word2vec(words[i]))

100%|██████████████████████████████████████████████████████████████████████████████| 1605/1605 [00:32<00:00, 49.97it/s]


In [132]:
X_new=np.array(X3)

In [133]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size = 0.20, random_state = 0)

In [134]:
from sklearn.svm import SVC
model4 = SVC(kernel='rbf', random_state=0).fit(X_train, y_train)

In [135]:
from sklearn.metrics import accuracy_score,classification_report
y_pred = model4.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_pred,y_test))

0.4735202492211838
              precision    recall  f1-score   support

           0       0.40      0.66      0.50        58
           1       0.50      0.50      0.50       111
           2       0.62      0.35      0.45       125
           3       0.31      0.52      0.39        27

    accuracy                           0.47       321
   macro avg       0.46      0.51      0.46       321
weighted avg       0.51      0.47      0.47       321



In [136]:
from sklearn.ensemble import RandomForestClassifier

In [137]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 150, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10,300,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [10, 25, 41, 56, 72, 87, 103, 118, 134, 150], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 42, 74, 106, 138, 171, 203, 235, 267, 300], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [138]:
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 42, 74, 106, 138, 171,
                                                      203, 235, 267, 300],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [10, 25, 41, 56, 72, 87,
                                                         103, 118, 134, 150]},
                   random_state=100, verbose=2)

In [139]:
rf_randomcv.best_params_

{'n_estimators': 103,
 'min_samples_split': 5,
 'min_samples_leaf': 6,
 'max_features': 'sqrt',
 'max_depth': 42,
 'criterion': 'gini'}

In [140]:
best_random_grid=rf_randomcv.best_estimator_

In [141]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
y_pred=best_random_grid.predict(X_test)
print(metrics.confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[36 22 29  7]
 [ 7 57 40  7]
 [ 8 16 45  2]
 [ 8  9  9 19]]
Accuracy Score 0.48909657320872274
Classification report:               precision    recall  f1-score   support

           0       0.61      0.38      0.47        94
           1       0.55      0.51      0.53       111
           2       0.37      0.63      0.46        71
           3       0.54      0.42      0.48        45

    accuracy                           0.49       321
   macro avg       0.52      0.49      0.48       321
weighted avg       0.53      0.49      0.49       321



In [142]:
from tqdm import tqdm
tqdm.pandas(desc="progress-bar")
from gensim.models import Doc2Vec
from sklearn import utils
import gensim
from gensim.models.doc2vec import TaggedDocument
import re

In [146]:
def label_sentences(corpus, label_type):
    """
    Gensim's Doc2Vec implementation requires each document/paragraph to have a label associated with it.
    We do this by using the TaggedDocument method. The format will be "TRAIN_i" or "TEST_i" where "i" is
    a dummy index of the post.
    """
    labeled = []
    for i, v in enumerate(corpus):
        label = label_type + '_' + str(i)
        labeled.append(gensim.models.doc2vec.TaggedDocument(v.split(), [label]))
    return labeled

In [147]:
X_train, X_test, y_train, y_test = train_test_split(np.asarray(corpus), y, test_size = 0.2, random_state = 24)

In [148]:
X_train = label_sentences(X_train, 'Train')
X_test = label_sentences(X_test, 'Test')
all_data = X_train + X_test

In [149]:
model_dbow = Doc2Vec(dm=0, vector_size=300, negative=5, min_count=1, alpha=0.065, min_alpha=0.065)
model_dbow.build_vocab([x for x in tqdm(all_data)])

100%|█████████████████████████████████████████████████████████████████████████| 1605/1605 [00:00<00:00, 1491659.19it/s]


In [150]:
for epoch in range(30):
    model_dbow.train(utils.shuffle([x for x in tqdm(all_data)]), total_examples=len(all_data), epochs=1)
    model_dbow.alpha -= 0.002
    model_dbow.min_alpha = model_dbow.alpha

100%|██████████████████████████████████████████████████████████████████████████████████████| 1605/1605 [00:00<?, ?it/s]


In [151]:
def get_vectors(model, corpus_size, vectors_size, vectors_type):
    """
    Get vectors from trained doc2vec model
    :param doc2vec_model: Trained Doc2Vec model
    :param corpus_size: Size of the data
    :param vectors_size: Size of the embedding vectors
    :param vectors_type: Training or Testing vectors
    :return: list of vectors
    """
    vectors = np.zeros((corpus_size, vectors_size))
    for i in range(0, corpus_size):
        prefix = vectors_type + '_' + str(i)
        vectors[i] = model.docvecs[prefix]
    return vectors

In [152]:
train_vectors_dbow = get_vectors(model_dbow, len(X_train), 300, 'Train')
test_vectors_dbow = get_vectors(model_dbow, len(X_test), 300, 'Test')

In [153]:
logreg = LogisticRegression(n_jobs=1, C=1e5)
logreg.fit(train_vectors_dbow, y_train)

LogisticRegression(C=100000.0, n_jobs=1)

In [154]:
logreg = logreg.fit(train_vectors_dbow, y_train)
y_pred = logreg.predict(test_vectors_dbow)

In [156]:
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

accuracy 0.4205607476635514
              precision    recall  f1-score   support

           0       0.51      0.50      0.51        86
           1       0.44      0.38      0.41        99
           2       0.35      0.32      0.34        87
           3       0.37      0.53      0.44        49

    accuracy                           0.42       321
   macro avg       0.42      0.43      0.42       321
weighted avg       0.42      0.42      0.42       321

